select
tenant_id
,account_name
,study_id
,study_country_id
,study_site_id
,person_id
,artifact_rule_id
,lifecycle_type_id
,process_adhoc_lifecycle_type_id
,artifact_id
,milestone_artifact_key
,submit_activity_id
,approval_activity_id
,on_holded_by_id
,terminated_by_id
,clinical_level
,artifact_level
,study_name
,amendment_name
,process_name
,country_code
,site_number
,person_first_name
,person_last_name
,artifact_profile_name
,artifact_name
,artifact_version
,document_date
,artifact_type
,document_type
,document_sub_type
,is_for_subcommittee
,lifecycle_type_name
,status
,version_label
,description
,file_uri
,tmf_zone_name
,tmf_section_name
,tmf_artifact_name
,category_name
,submission_activity_name
,approval_activity_name
,udf_submission_category_name
,udf_submission_type_name
,udf_submission_reason
,submission_meeting_date
,submission_next_meeting_date
,submission_date
,submission_approval_date
,pre_ip_release_review
,post_ip
,expiry_date
,manage_document_expiry
,days_until_expiry_notification
,show_person_name
,first_shared_date
,last_shared_date
,last_shared_user_name
,contract_amendment_reason
,contract_amendment_revision
,contract_status
,enable_on_hold
,enable_terminate
,on_holded_at
,on_holded_user_name
,terminated_at
,terminated_user_name
,total_activities
,completed_activities
,percentage_completed
,adhoc
,created_at
,updated_at
from public.study_level_artifacts;
