select
tenant_id
,account_name
,study_id
,study_name
,protocol_name
,cro_study_name
,full_name
,status
,process_name
,compound_name
,therapeutic_area
,flex_string_1
,flex_string_2
,flex_long_string_1
,created_at
,updated_at
,source_organization_type
,sponsor_study_name
,project_number
,short_title
,general_indication
,specific_indication
,study_phase
,source_study_status
,sponsor_organization_name
,cro_organization_name
from public.studies;
